defmodule UspsEx.Classid do
  defstruct ratev4: [
              "0": "First-ClassMail;LargeEnvelope",
              "0": "First-ClassMail;StampedLetter",
              "0": "First-ClassPackageService-Retail",
              "0": "First-ClassMail;Postcards",
              "1": "PriorityMail",
              "2": "PriorityMailExpress;HoldForPickup",
              "3": "PriorityMailExpress",
              "4": "StandardPost",
              "5": "BoundPrintedMatterParcels",
              "6": "MediaMailParcel",
              "7": "LibraryMailParcel",
              "13": "PriorityMailExpress;FlatRateEnvelope",
              "15": "First-ClassMail;LargePostcards",
              "16": "PriorityMail;FlatRateEnvelope",
              "17": "PriorityMail;MediumFlatRateBox",
              "20": "BoundPrintedMatterFlats",
              "22": "PriorityMail;LargeFlatRateBox",
              "23": "PriorityMailExpress;Sunday/HolidayDelivery",
              "25": "PriorityMailExpress;Sunday/HolidayDeliveryFlatRateEnvelope",
              "27": "PriorityMailExpress;FlatRateEnvelopeHoldForPickup",
              "28": "PriorityMail;SmallFlatRateBox",
              "29": "PriorityMail;PaddedFlatRateEnvelope",
              "30": "PriorityMailExpress;LegalFlatRateEnvelope",
              "31": "PriorityMailExpress;LegalFlatRateEnvelopeHoldForPickup",
              "32": "PriorityMailExpress;Sunday/HolidayDeliveryLegalFlatRateEnvelope",
              "33": "PriorityMail;HoldForPickup",
              "34": "PriorityMail;LargeFlatRateBoxHoldForPickup",
              "35": "PriorityMail;MediumFlatRateBoxHoldForPickup",
              "36": "PriorityMail;SmallFlatRateBoxHoldForPickup",
              "37": "PriorityMail;FlatRateEnvelopeHoldForPickup",
              "38": "PriorityMail;GiftCardFlatRateEnvelope",
              "39": "PriorityMail;GiftCardFlatRateEnvelopeHoldForPickup",
              "40": "PriorityMail;WindowFlatRateEnvelope",
              "41": "PriorityMail;WindowFlatRateEnvelopeHoldForPickup",
              "42": "PriorityMail;SmallFlatRateEnvelope",
              "43": "PriorityMail;SmallFlatRateEnvelopeHoldForPickup",
              "44": "PriorityMail;LegalFlatRateEnvelope",
              "45": "PriorityMail;LegalFlatRateEnvelopeHoldForPickup",
              "46": "PriorityMail;PaddedFlatRateEnvelopeHoldForPickup",
              "47": "PriorityMail;RegionalRateBoxA",
              "48": "PriorityMail;RegionalRateBoxAHoldForPickup",
              "49": "PriorityMail;RegionalRateBoxB",
              "50": "PriorityMail;RegionalRateBoxBHoldForPickup",
              "53": "First-Class;PackageServiceHoldForPickup",
              "55": "PriorityMailExpress;FlatRateBoxes",
              "56": "PriorityMailExpress;FlatRateBoxesHoldForPickup",
              "57": "PriorityMailExpress;Sunday/HolidayDeliveryFlatRateBoxes",
              "58": "PriorityMail;RegionalRateBoxC",
              "59": "PriorityMail;RegionalRateBoxCHoldForPickup",
              "61": "First-Class;PackageService",
              "62": "PriorityMailExpress;PaddedFlatRateEnvelope",
              "63": "PriorityMailExpress;PaddedFlatRateEnvelopeHoldForPickup",
              "64": "PriorityMailExpress;Sunday/HolidayDeliveryPaddedFlatRateEnvelope",
              "77": "ParcelSelectGround",
              "78": "First-ClassMail;MeteredLetter",
              "82": "ParcelSelectLightweightMachinableParcels5-Digit",
              "82": "ParcelSelectLightweightIrregularParcels5-Digit",
              "82": "ParcelSelectLightweightMachinableParcelsNDC",
              "82": "ParcelSelectLightweightIrregularParcelsNDC",
              "82": "ParcelSelectLightweightMachinableParcelsMixedNDC",
              "82": "ParcelSelectLightweightIrregularParcelsMixedNDC",
              "82": "ParcelSelectLightweightIrregularParcelsSCF",
              "84": "PriorityMailCubic",
              "88": "USPSConnectLocalDDU",
              "89": "USPSConnectLocalFlatRateBag–SmallDDU",
              "90": "USPSConnectLocalFlatRateBag–LargeDDU",
              "91": "USPSConnectLocalFlatRateBoxDDU",
              "92": "ParcelSelectGroundCubic",
              "179": "ParcelSelectDestinationEntryMachinableDDU",
              "179": "ParcelSelectDestinationEntryNonmachinableDDU",
              "179": "ParcelSelectDestinationEntryMachinableDSCF5D",
              "179": "ParcelSelectDestinationEntryNonmachinableDSCF5-Digit",
              "179": "ParcelSelectDestinationEntryMachinableDSCFSCF",
              "179": "ParcelSelectDestinationEntryNonmachinableDSCF3-Digit",
              "179": "ParcelSelectDestinationEntryMachinableDNDC",
              "179": "ParcelSelectDestinationEntryNonmachinableDNDC",
              "922": "PriorityMailReturnServicePaddedFlatRateEnvelope",
              "932": "PriorityMailReturnServiceGiftCardFlatRateEnvelope",
              "934": "PriorityMailReturnServiceWindowFlatRateEnvelope",
              "936": "PriorityMailReturnServiceSmallFlatRateEnvelope",
              "938": "PriorityMailReturnServiceLegalFlatRateEnvelope",
              "939": "PriorityMailReturnServiceFlatRateEnvelope",
              "946": "PriorityMailReturnServiceRegionalRateBoxA",
              "947": "PriorityMailReturnServiceRegionalRateBoxB",
              "962": "PriorityMailReturnService",
              "963": "PriorityMailReturnServiceLargeFlatRateBox",
              "964": "PriorityMailReturnServiceMediumFlatRateBox",
              "965": "PriorityMailReturnServiceSmallFlatRateBox",
              "967": "PriorityMailReturnServiceCubic",
              "968": "First-ClassPackageReturnService",
              "969": "GroundReturnService",
              "2020": "BoundPrintedMatterFlatsHoldForPickup",
              "2071": "ParcelSelectGround;HoldForPickup",
              "2077": "BoundPrintedMatterParcelsHoldForPickup",
              "2082": "ParcelSelectLightweightMachinableParcels5-DigitHoldForPickup",
              "2082": "ParcelSelectLightweightIrregularParcels5-DigitHoldForPickup",
              "2082": "ParcelSelectLightweightMachinableParcelsNDCHoldForPickup",
              "2082": "ParcelSelectLightweightIrregularParcelsNDCHoldForPickup",
              "2082": "ParcelSelectLightweightMachinableParcelsMixedNDCHoldForPickup",
              "2082": "ParcelSelectLightweightIrregularParcelsMixedNDCHoldForPickup",
              "2082": "ParcelSelectLightweightIrregularParcelsSCFHoldForPickup"
            ],
            ratev6: [
              "1": "Priority Mail Express International",
              "2": "Priority Mail International",
              "4": "Global Express Guaranteed; (GXG)**",
              "5": "Global Express Guaranteed; Document",
              "6": "Global Express Guarantee; Non-Document Rectangular",
              "7": "Global Express Guaranteed; Non-Document Non-Rectangular",
              "8": "Priority Mail International; Flat Rate Envelope**",
              "9": "Priority Mail International; Medium Flat Rate Box",
              "10": "Priority Mail Express International; Flat Rate Envelope",
              "11": "Priority Mail International; Large Flat Rate Box",
              "12": "USPS GXG; Envelopes**",
              "13": "First-Class Mail; International Letter**",
              "14": "First-Class Mail; International Large Envelope**",
              "15": "First-Class Package International Service**",
              "16": "Priority Mail International; Small Flat Rate Box**",
              "17": "Priority Mail Express International; Legal Flat Rate Envelope",
              "18": "Priority Mail International; Gift Card Flat Rate Envelope**",
              "19": "Priority Mail International; Window Flat Rate Envelope**",
              "20": "Priority Mail International; Small Flat Rate Envelope**",
              "1": "Priority Mail Express International",
              "2": "Priority Mail International",
              "4": "Global Express Guaranteed; (GXG)**",
              "5": "Global Express Guaranteed; Document",
              "6": "Global Express Guarantee; Non-Document Rectangular",
              "7": "Global Express Guaranteed; Non-Document Non-Rectangular",
              "8": "Priority Mail International; Flat Rate Envelope**",
              "9": "Priority Mail International; Medium Flat Rate Box",
              "10": "Priority Mail Express International; Flat Rate Envelope",
              "11": "Priority Mail International; Large Flat Rate Box",
              "12": "USPS GXG; Envelopes**",
              "13": "First-Class Mail; International Letter**",
              "14": "First-Class Mail; International Large Envelope**",
              "15": "First-Class Package International Service**",
              "16": "Priority Mail International; Small Flat Rate Box**",
              "17": "Priority Mail Express International; Legal Flat Rate Envelope",
              "18": "Priority Mail International; Gift Card Flat Rate Envelope**",
              "19": "Priority Mail International; Window Flat Rate Envelope**",
              "20": "Priority Mail International; Small Flat Rate Envelope**",
              "28": "Airmail M-Bag"
            ]
end