openapi: 3.0.3
info:
  title: Service Standards File Download API
  version: 3.0.0
  description: |
    The Service Standards File Download API provides a secure and efficient way to manage file downloads. It consists of three main functionalities:

    1. **Discovery of Available Files**: Retrieve a list of files that are available for download.
    2. **File Download with Byte-Range Support**: Download files with support for byte-range requests, which is useful for large files. The API enforces a 10MB limit on the byte range to ensure efficient and manageable downloads.

    ### Workflow
    1. **Discover Available Files**: Use the `/files` endpoint to get a list of files available for download.
    2. **Download File**: Use the `/file-download` endpoint to download the file. If the file is larger than 10MB (10485760 bytes) use the `Range` header to specify the byte range to download.

    This API is for large shippers to be able to download large service standards files so they can be consumed programmatically and not require manual intervention.
paths:
  /files:
    get:
      summary: List available files for download
      operationId: get-files-list
      responses:
        '200':
          description: A list of available files
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Links'
              examples:
                filesExample:
                  $ref: '#/components/examples/FilesList'
  /file-download:
    get:
      summary: Download the file using the signed URL
      operationId: get-file-download
      parameters:
        - name: token
          in: query
          required: true
          schema:
            type: string
            example: abcd1234efgh5678ijkl9012mnop3456
          description: |
            The token query parameter is a mandatory security feature required to authenticate and authorize the download request. This token is typically a unique string generated by the server, often during the user login or session initiation process. It ensures that only authorized users can access and download the requested resources.
        - name: Range
          in: header
          required: false
          schema:
            type: string
            default: bytes=0-10485759
            example: bytes=0-10485759
          description: |
            Specifies the range of bytes to be downloaded. The range should not exceed 10MB (10485760 bytes).
            Consumers are responsible for keeping track of their offset for subsequent requests. The default range is 0 to 10MB.
      responses:
        '200':
          description: File downloaded successfully
          content:
            application/zip:
              schema:
                type: string
                format: binary
          headers:
            Content-Length:
              description: The size of the content being sent in this response
              schema:
                type: integer
                example: 1048575
        '206':
          description: Partial content downloaded successfully
          content:
            application/zip:
              schema:
                type: string
                format: binary
          headers:
            Content-Range:
              description: The range of bytes being sent and the total size of the file
              schema:
                type: string
                example: bytes 0-1048575/3145728
            Content-Length:
              description: The size of the content being sent in this response
              schema:
                type: integer
                example: 1048576
        '403':
          description: Forbidden or expired URL
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
        '416':
          description: Requested range not satisfiable
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'
          headers:
            Range-limit:
              description: The range of bytes being requested cannot exceed 10MB
              schema:
                type: string
                example: bytes=0-10485759
        '404':
          description: File not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorMessage'

components:
  schemas:
    Links:
      title: Hypermedia Links
      description: Hypermedia links to related resources.
      type: array
      items:
        type: object
        required:
          - rel
          - href
        properties:
          rel:
            description: The short name(s) of the relationship corresponding to the link.
            type: array
            items:
              type: string
          title:
            description: A human-readable title of the link relationship.
            type: string
          description:
            description: A human-readable description of the link relationship.
            type: string
          href:
            description: The URL to a related resource.
            type: string
            format: uri
          method:
            type: string
            description: The HTTP method to use to access this link.
            enum:
              - GET
              - POST
              - PUT
              - DELETE
          submissionMediaType:
            description: The media type of the resource request.
            type: string
          targetMediaType:
            description: The media type of the resource response.
            type: string
        additionalProperties: false
    ErrorMessage:
      title: Error
      type: object
      properties:
        apiVersion:
          type: string
          description: The version of the API that was used and that raised the error.
        error:
          type: object
          properties:
            code:
              type: string
              description: The error status code that has been returned in response to the request.
            message:
              type: string
              description: A human-readable message describing the error.
            errors:
              type: array
              items:
                type: object
                properties:
                  status:
                    type: string
                    description: The status code response returned to the client.
                  code:
                    type: string
                    description: An internal subordinate code used for error diagnosis.
                  title:
                    type: string
                    description: A human-readable title that identifies the error.
                  detail:
                    type: string
                    description: A human-readable description of the error that occurred.
                  source:
                    type: object
                    properties:
                      parameter:
                        type: string
                        description: The input in the request which caused an error.
                      example:
                        type: string
                        description: An example of a valid value for the input parameter.
                    additionalProperties: true
                    description: The element that is suspected of originating the error. Helps to pinpoint the problem.
          additionalProperties: true
          description: The high-level error that has occurred as indicated by the status code.
      additionalProperties: true
      description: Standard error message response.
  examples:
    FilesList:
      description: List of files currently available for download
      summary: List of files
      value: |
        [
          {
            "rel": [
              "self"
            ],
            "title": "Complete Service Standard Data",
            "href": "https://ssmp.usps.gov/files/f47ac10b-58cc-4372-a567-0e02b2c3d479/generate-signed-url",
            "method": "GET",
            "targetMediaType": "application/zip"
          },
          {
            "rel": [
              "self"
            ],
            "title": "Base Service Standard Data",
            "href": "https://ssmp.usps.gov/files/d2a5d59c-5d38-4f7e-9c13-1d9f9b1bc0c3/generate-signed-url",
            "method": "GET",
            "targetMediaType": "application/zip"
          },
          {
            "rel": [
              "self"
            ],
            "title": "Service Standard Exception Data",
            "href": "https://ssmp.usps.gov/files/a6d3b4c6-f9e0-4b8b-8e1c-5b8f4d2b5a78/generate-signed-url",
            "method": "GET",
            "targetMediaType": "application/zip"
          }
        ]
  headers:
    WWWAuthenticate:
      description: Hint to the client application which security scheme to authorize a resource request.
      required: false
      schema:
        type: string
        example: "WWW-Authenticate: Bearer realm=\"https://api.usps.com\""
    RetryAfter:
      description: Indicate to the client application a time after which they can retry a resource request.
      required: false
      schema:
        type: string
        example: "Retry-After: 30"
  securitySchemes:
    OAuth:
      type: oauth2
      description: The specified APIs accept an access token formatted as a JSON Web Token. The relative path to the OAuth2 version 3 API which supplies this access token is provided below for reference.
      flows:
        clientCredentials:
          tokenUrl: /oauth2/v3/token
          scopes:
            addresses: read-only access to all addresses endpoints
        authorizationCode:
          authorizationUrl: /oauth2/v3/authorize
          tokenUrl: /oauth2/v3/token
          scopes:
            addresses: read-only access to all addresses endpoints
